name: sqlalchemy

services:
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: sqlalchemy
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: oleg
    ports:
      - "5433:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=oyapparov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "8888:80"
  app:
    container_name: sqlalchemy
    image: oleg/sqlalchemy